[workspace]
authors = ["fragilefort <imaddex3759@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "oxytribe"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
nextflow = ">=26.4.1,<27"
nf-core = ">=4.0.2,<5"
rust = ">=1.96.0,<1.97"
c-compiler = ">=1.11.0,<2"
sra-tools = ">=3.4.1,<4"
r-here = ">=1.0.2,<2"

[tasks]
download-test-data = "bash workflow/contract/test/download_test_data.sh"
test-docker = { cmd = "nextflow run workflow/main.nf -profile test,docker", depends-on = ["download-test-data"] }
test-singularity = { cmd = "nextflow run workflow/main.nf -profile test,singularity", depends-on = ["download-test-data"] }
validation = "Rscript workflow/bin/validate.r"
